apiVersion: v1
kind: Service
metadata:
  name: cluster-insight
  namespace: default
  labels:
    app: cluster-insight
    version: v2
spec:
  selector:
    app: cluster-insight
    version: v2
  ports:
    - name: cluster-insight
      port: 5555
      targetPort: cluster-insight
